device:
  layer: rpizero2w
  hostname: ghostcam
  user1: ghostcam
  user1pass: ghostcam

image:
  layer: image-rpios
  boot_part_size: 512M
  root_part_size: 4G
  name: ghostcam-zero2w

layer:
  base: bookworm-minbase
  ghostcam: ghostcam
