package main

import (
	"fmt"

	"github.com/pulumi/pulumi-command/sdk/go/command/local"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi/config"
)

// StripeOutputs holds secrets generated by Stripe provisioning.
type StripeOutputs struct {
	WebhookSecret  pulumi.StringOutput
	PortalConfigID pulumi.StringOutput
}

// stripeProduct creates a Stripe product with ghostcam billing metadata.
// Returns the product ID as Stdout.
func stripeProduct(
	ctx *pulumi.Context,
	name, displayName, cameraLimit, storageGB string,
	apiKey pulumi.StringInput,
) (*local.Command, error) {
	return local.NewCommand(ctx, "stripe-product-"+name, &local.CommandArgs{
		Create: pulumi.Sprintf(
			`curl -sf -X POST https://api.stripe.com/v1/products `+
				`-u "$STRIPE_API_KEY:" `+
				`-d "name=%s" `+
				`-d "metadata[ghostcam_tier]=%s" `+
				`-d "metadata[ghostcam_camera_limit]=%s" `+
				`-d "metadata[ghostcam_storage_gb]=%s" `+
				`| jq -r '.id'`,
			displayName, name, cameraLimit, storageGB,
		),
		Environment: pulumi.StringMap{"STRIPE_API_KEY": apiKey},
	}, pulumi.RetainOnDelete(true))
}

// stripePrice creates a recurring monthly price attached to a product.
// Returns the price ID as Stdout.
func stripePrice(
	ctx *pulumi.Context,
	name string,
	productID pulumi.StringInput,
	cents string,
	apiKey pulumi.StringInput,
) (*local.Command, error) {
	return local.NewCommand(ctx, "stripe-price-"+name, &local.CommandArgs{
		Create: pulumi.Sprintf(
			`curl -sf -X POST https://api.stripe.com/v1/prices `+
				`-u "$STRIPE_API_KEY:" `+
				`-d "product=%s" `+
				`-d "unit_amount=%s" `+
				`-d "currency=usd" `+
				`-d "recurring[interval]=month" `+
				`| jq -r '.id'`,
			productID, cents,
		),
		Environment: pulumi.StringMap{"STRIPE_API_KEY": apiKey},
	}, pulumi.RetainOnDelete(true))
}

func setupStripe(ctx *pulumi.Context, cfg *config.Config, fly *FlyOutputs) (*StripeOutputs, error) {
	apiKey := cfg.RequireSecret("stripeSecretKey")
	hostname := cfg.Require("hostname")

	// ── Products ──────────────────────────────────────────────────────
	starter, err := stripeProduct(ctx, "starter", "Starter", "4", "50", apiKey)
	if err != nil {
		return nil, err
	}
	pro, err := stripeProduct(ctx, "pro", "Pro", "16", "500", apiKey)
	if err != nil {
		return nil, err
	}
	enterprise, err := stripeProduct(ctx, "enterprise", "Enterprise", "64", "5000", apiKey)
	if err != nil {
		return nil, err
	}

	// ── Prices ────────────────────────────────────────────────────────
	starterPrice, err := stripePrice(ctx, "starter", starter.Stdout, cfg.Require("starterPriceCents"), apiKey)
	if err != nil {
		return nil, err
	}
	proPrice, err := stripePrice(ctx, "pro", pro.Stdout, cfg.Require("proPriceCents"), apiKey)
	if err != nil {
		return nil, err
	}
	enterprisePrice, err := stripePrice(ctx, "enterprise", enterprise.Stdout, cfg.Require("enterprisePriceCents"), apiKey)
	if err != nil {
		return nil, err
	}

	// ── Webhook endpoint ──────────────────────────────────────────────
	events := []string{
		"checkout.session.completed",
		"customer.subscription.updated",
		"customer.subscription.deleted",
		"product.created",
		"product.updated",
		"product.deleted",
		"price.created",
		"price.updated",
		"price.deleted",
	}
	var eventFlags string
	for _, e := range events {
		eventFlags += fmt.Sprintf(`-d "enabled_events[]=%s" `, e)
	}

	webhook, err := local.NewCommand(ctx, "stripe-webhook", &local.CommandArgs{
		Create: pulumi.Sprintf(
			`curl -sf -X POST https://api.stripe.com/v1/webhook_endpoints `+
				`-u "$STRIPE_API_KEY:" `+
				`-d "url=https://%s/api/v1/webhooks/stripe" `+
				`%s`+
				`| jq -r '.secret'`,
			hostname, eventFlags,
		),
		Environment: pulumi.StringMap{"STRIPE_API_KEY": apiKey},
	}, pulumi.RetainOnDelete(true))
	if err != nil {
		return nil, err
	}

	// ── Customer portal ───────────────────────────────────────────────
	// Needs all 3 product IDs + price IDs for plan switching.
	portal, err := local.NewCommand(ctx, "stripe-portal", &local.CommandArgs{
		Create: pulumi.All(
			starter.Stdout, starterPrice.Stdout,
			pro.Stdout, proPrice.Stdout,
			enterprise.Stdout, enterprisePrice.Stdout,
		).ApplyT(func(args []interface{}) string {
			sProd, sPrice := args[0].(string), args[1].(string)
			pProd, pPrice := args[2].(string), args[3].(string)
			eProd, ePrice := args[4].(string), args[5].(string)
			return fmt.Sprintf(
				`curl -sf -X POST https://api.stripe.com/v1/billing_portal/configurations `+
					`-u "$STRIPE_API_KEY:" `+
					`-d "business_profile[headline]=Manage your Ghostcam subscription" `+
					`-d "features[subscription_update][enabled]=true" `+
					`-d "features[subscription_update][default_allowed_updates][]=price" `+
					`-d "features[subscription_update][products][0][product]=%s" `+
					`-d "features[subscription_update][products][0][prices][]=%s" `+
					`-d "features[subscription_update][products][1][product]=%s" `+
					`-d "features[subscription_update][products][1][prices][]=%s" `+
					`-d "features[subscription_update][products][2][product]=%s" `+
					`-d "features[subscription_update][products][2][prices][]=%s" `+
					`-d "features[subscription_cancel][enabled]=true" `+
					`-d "features[subscription_cancel][mode]=at_period_end" `+
					`| jq -r '.id'`,
				sProd, sPrice, pProd, pPrice, eProd, ePrice,
			)
		}).(pulumi.StringOutput),
		Environment: pulumi.StringMap{"STRIPE_API_KEY": apiKey},
	}, pulumi.RetainOnDelete(true))
	if err != nil {
		return nil, err
	}

	return &StripeOutputs{
		WebhookSecret:  webhook.Stdout,
		PortalConfigID: portal.Stdout,
	}, nil
}
