# Generated by tools/pydanticgen — do not edit.
# Source: common/telemetry.go
from __future__ import annotations

from pydantic import BaseModel, ConfigDict, Field


class TelemetryDatagram(BaseModel):
    """TelemetryDatagram contains sensor readings from the camera.
Pointer fields implement omitempty — only non-nil fields are serialized."""

    model_config = ConfigDict(populate_by_name=True)

    ts: int
    sig: int | None = Field(default=None)
    temp: int | None = Field(default=None)
    fps: float | None = Field(default=None)
    kbps: int | None = Field(default=None)
    cpu: int | None = Field(default=None)
    mem: int | None = Field(default=None)
    uptime: int | None = Field(default=None)
    lat: float | None = Field(default=None)
    lon: float | None = Field(default=None)
    alt: float | None = Field(default=None)
    gps_fix: int | None = Field(default=None)
    power_mode: str | None = Field(default=None)
    upload_mode: str | None = Field(default=None)
    battery_pct: int | None = Field(default=None)


TelemetryDatagram.model_rebuild()
