# Generated by tools/pydanticgen — do not edit.
# Source: common/types.go
from __future__ import annotations

from pydantic import BaseModel, ConfigDict, Field

from ghostcam.wire.telemetry import TelemetryDatagram


class ProvisionRequest(BaseModel):
    """ProvisionRequest is sent by the camera during provisioning. The camera
sends its ed25519 public key for registration (like adding to SSH
authorized_keys). The server derives device_id from the public key."""

    model_config = ConfigDict(populate_by_name=True)

    token: str
    device_serial: str
    public_key: str
    fw_version: str | None = Field(default=None)

class ProvisionResponse(BaseModel):
    """ProvisionResponse acknowledges key registration. No secret is returned."""

    model_config = ConfigDict(populate_by_name=True)

    device_id: str
    status: str

class TelemetryPollRequest(BaseModel):
    """TelemetryPollRequest is sent by the camera every 10s with current sensor readings."""

    model_config = ConfigDict(populate_by_name=True)

    telemetry: TelemetryDatagram
    fw_version: str | None = Field(default=None)

class TelemetryPollResponse(BaseModel):
    """TelemetryPollResponse contains any pending commands for the camera.

WakeLive is set when a viewer is actively trying to watch a camera that
is in standby mode (live WS not currently connected). The camera reads
this flag and proactively opens its live WebSocket so WebRTC startup
stays bounded by one telemetry-poll interval."""

    model_config = ConfigDict(populate_by_name=True)

    commands: list[CameraCommand] | None = Field(default=None)
    wake_live: bool | None = Field(default=None)

class CameraCommand(BaseModel):
    """CameraCommand is a tagged union of commands the server can send to a camera.
The Type field determines which other fields are populated.

Power-mode commands:
  - set_power_mode      → PowerMode field      (live | standby | sleep)
  - set_upload_mode     → UploadMode field     (proactive | lazy)
  - set_schedule        → Schedule field       (JSON-encoded windows)
  - set_battery_rules   → BatteryRules field   (JSON-encoded thresholds)
  - upload_segments     → SegmentIDs field     (lazy-mode on-demand fetch)"""

    model_config = ConfigDict(populate_by_name=True)

    type: str
    mode: str | None = Field(default=None)
    resolution: str | None = Field(default=None)
    ssid: str | None = Field(default=None)
    psk: str | None = Field(default=None)
    power_mode: str | None = Field(default=None)
    upload_mode: str | None = Field(default=None)
    schedule: str | None = Field(default=None)
    battery_rules: str | None = Field(default=None)
    segment_ids: list[str] | None = Field(default=None)

class PresignRequest(BaseModel):
    """PresignRequest requests presigned PUT URLs and confirms previously
uploaded segments. The `pending` field declares segments the camera
is *about* to upload but hasn't yet — server uses it to surface a
"blue ghost" placeholder in the viewer timeline before the actual
S3 PUT lands. Lags upload by at most one presign cycle, which is
still way faster than waiting for the confirm-on-next-cycle round
trip the timeline currently uses."""

    model_config = ConfigDict(populate_by_name=True)

    count: int
    uploaded: list[UploadedSegment] | None = Field(default=None)
    pending: list[UploadedSegment] | None = Field(default=None)

class UploadedSegment(BaseModel):
    """UploadedSegment confirms a successfully uploaded segment."""

    model_config = ConfigDict(populate_by_name=True)

    segment_id: str
    start_ts: int
    end_ts: int
    size_bytes: int
    has_motion: bool | None = Field(default=None)

class PresignedUrl(BaseModel):
    """PresignedUrl is a presigned URL for uploading a segment to S3/Tigris."""

    model_config = ConfigDict(populate_by_name=True)

    segment_id: str
    s3_key: str
    put_url: str
    expires_at: int

class PresignResponse(BaseModel):
    """PresignResponse contains presigned URLs for segment uploads."""

    model_config = ConfigDict(populate_by_name=True)

    urls: list[PresignedUrl]
    init_url: PresignedUrl | None = Field(default=None)
    storage_capped: bool | None = Field(default=None)

class LocalManifestRequest(BaseModel):
    """LocalManifestRequest is the body of
POST /api/v1/cameras/{deviceID}/local-manifest. A lazy-mode camera
posts a manifest of segments it has on disk but has NOT yet uploaded
to S3, so the server's timeline / coverage bar can show the user
that footage exists even if it's not fetchable until they scrub to
it. On scrub, the server queues an `upload_segments` command which
pulls the bytes on demand.

Manifest entries are inserted with `uploaded_to_s3 = FALSE`. When
the camera later uploads a segment (because of a scrub-triggered
command), the presign-confirm path flips it to TRUE."""

    model_config = ConfigDict(populate_by_name=True)

    segments: list[UploadedSegment]

class QRPayload(BaseModel):
    """QRPayload is the JSON shape encoded inside a provisioning QR code. The
viewer UI builds it (via the server's EnrollmentQR handler), displays
it as a QR image, and the camera parses it on first boot after scan.
Field names are single letters to keep the QR code compact."""

    model_config = ConfigDict(populate_by_name=True)

    s: str
    t: str
    w: str | None = Field(default=None)
    p: str | None = Field(default=None)


ProvisionRequest.model_rebuild()
ProvisionResponse.model_rebuild()
TelemetryPollRequest.model_rebuild()
TelemetryPollResponse.model_rebuild()
CameraCommand.model_rebuild()
PresignRequest.model_rebuild()
UploadedSegment.model_rebuild()
PresignedUrl.model_rebuild()
PresignResponse.model_rebuild()
LocalManifestRequest.model_rebuild()
QRPayload.model_rebuild()
