// Code generated by tygo. DO NOT EDIT.

//////////
// source: apitypes.go
/*
Package apitypes defines every request, response, and event payload on
the viewer-server HTTP/SSE surface. It exists so tygo can generate a
matching TypeScript file for the UI — editing a struct here is
automatically reflected in ui/src/lib/api-types/ on the next
`go generate ./...` run, and CI refuses PRs whose generated file is
stale.

Rules for this package:

 1. Every type is exported and has JSON tags that exactly match the
    wire format. The struct field names are internal; the tags are
    the contract.
 2. No behavior, no methods that do work. Types only. This keeps the
    package importable from anywhere without cycles.
 3. Camera-server contract types (PresignRequest, TelemetryDatagram,
    ProvisionRequest, etc.) stay in common/. This package is the
    viewer-server surface. The two do not overlap by design.
*/

/**
 * LoginRequest is the body of POST /api/v1/auth/login.
 */
export interface LoginRequest {
  email: string;
  password: string;
}
/**
 * LoginResponse is the body of POST /api/v1/auth/login on success.
 */
export interface LoginResponse {
  user_id: string;
}
/**
 * ChangePasswordRequest is the body of PATCH /api/v1/auth/password.
 */
export interface ChangePasswordRequest {
  current_password: string;
  new_password: string;
}
/**
 * ForgotPasswordRequest is the body of POST /api/v1/auth/forgot-password.
 */
export interface ForgotPasswordRequest {
  email: string;
}
/**
 * ResetPasswordRequest is the body of POST /api/v1/auth/reset-password.
 */
export interface ResetPasswordRequest {
  token: string;
  new_password: string;
}
/**
 * VerifyEmailRequest is the body of POST /api/v1/auth/verify-email.
 */
export interface VerifyEmailRequest {
  token: string;
}
/**
 * ChangeEmailRequest is the body of PATCH /api/v1/auth/email.
 */
export interface ChangeEmailRequest {
  new_email: string;
  current_password: string;
}
/**
 * ConfirmEmailChangeRequest is the body of POST /api/v1/auth/email/confirm.
 */
export interface ConfirmEmailChangeRequest {
  token: string;
}
/**
 * RequestLoginOTPRequest is the body of POST /api/v1/auth/otp/request.
 */
export interface RequestLoginOTPRequest {
  email: string;
}
/**
 * VerifyLoginOTPRequest is the body of POST /api/v1/auth/otp/verify.
 */
export interface VerifyLoginOTPRequest {
  email: string;
  code: string;
}
/**
 * CameraResponse is the per-camera payload returned by GET /api/v1/cameras
 * (as a list) and GET /api/v1/cameras/{id} (as a single object).
 */
export interface CameraResponse {
  device_id: string;
  display_name: string;
  enrolled_at: number /* uint64 */;
  last_seen_at?: number /* int64 */;
  provisioned: boolean;
  notes?: string;
  resolution: string;
  recording_mode: string;
  fw_version?: string;
  telemetry?: TelemetryEntry;
  /**
   * PowerMode / UploadMode are the manually-set values from the
   * cameras row. The camera's actual effective mode (which may differ
   * when a schedule or battery rule is overriding) is reported back
   * via the telemetry datagram (TelemetryEntry.PowerMode etc).
   */
  power_mode: string;
  upload_mode: string;
  schedule?: any /* json.RawMessage */;
  battery_rules?: any /* json.RawMessage */;
}
/**
 * EnrollResponse is the body of POST /api/v1/cameras — a one-time
 * provisioning token plus its expiry.
 */
export interface EnrollResponse {
  token: string;
  expires_at: number /* uint64 */;
}
/**
 * UpdateCameraRequest is the body of PATCH /api/v1/cameras/{id}.
 * Power-mode fields:
 *   - PowerMode   — "live" | "standby" | "sleep"
 *   - UploadMode  — "proactive" | "lazy"
 *   - Schedule    — list of {start, end, days, power_mode, upload_mode}.
 *                   Send an empty list to clear an existing schedule.
 *   - BatteryRules — list of {threshold_pct, power_mode, upload_mode}.
 *                    Send an empty list to clear.
 * All four are optional; sending `null` leaves the existing value alone.
 */
export interface UpdateCameraRequest {
  display_name?: string;
  notes?: string;
  resolution?: string;
  recording_mode?: string;
  power_mode?: string;
  upload_mode?: string;
  schedule?: any /* json.RawMessage */;
  battery_rules?: any /* json.RawMessage */;
}
/**
 * DeleteFootageResponse is the body of DELETE
 * /api/v1/cameras/{deviceID}/footage. The endpoint processes deletions
 * in batches bounded by server-side limits; HasMore is true when the
 * batch was full, signalling the UI to call again to continue the
 * purge.
 */
export interface DeleteFootageResponse {
  deleted_count: number /* int */;
  bytes_freed: number /* uint64 */;
  has_more: boolean;
  remaining_count: number /* int */;
}
/**
 * TelemetryEntry is a single camera telemetry reading stored in the Redis
 * telemetry stream and returned on GET /api/v1/telemetry/{id}/latest,
 * GET /api/v1/telemetry/{id} and inside CameraResponse.
 */
export interface TelemetryEntry {
  ts: number /* uint64 */;
  server_ts: number /* uint64 */;
  sig?: number /* int8 */;
  temp?: number /* uint32 */;
  fps?: number /* float32 */;
  kbps?: number /* uint32 */;
  cpu?: number /* uint32 */;
  mem?: number /* uint32 */;
  uptime?: number /* uint32 */;
  lat?: number /* float64 */;
  lon?: number /* float64 */;
  alt?: number /* float32 */;
  gps_fix?: number /* uint8 */;
  /**
   * PowerMode / UploadMode are what the camera is CURRENTLY effective
   * at (after schedule + battery-rule resolution), which can differ
   * from the manually-set values on the cameras row. UI shows both
   * so the operator sees what their schedule is doing.
   */
  power_mode?: string;
  upload_mode?: string;
  /**
   * BatteryPct is 0–100 only when a battery-sensing HAT is wired up
   * (see GH issue #73). nil on grid-powered cameras.
   */
  battery_pct?: number /* uint8 */;
}
/**
 * TelemetryRangeResponse is the body of GET /api/v1/telemetry/{id}?from=&to=.
 */
export interface TelemetryRangeResponse {
  entries: TelemetryEntry[];
}
/**
 * PrepareClipRequest is the body of POST /api/v1/clips/prepare.
 */
export interface PrepareClipRequest {
  device_id: string;
  from_ms: number /* uint64 */;
  to_ms: number /* uint64 */;
}
/**
 * ClipSegment is one presigned segment URL inside PrepareClipResponse.
 */
export interface ClipSegment {
  id: string;
  url: string;
  start_ms: number /* uint64 */;
  end_ms: number /* uint64 */;
  size_bytes: number /* uint64 */;
}
/**
 * PrepareClipResponse is the body of POST /api/v1/clips/prepare.
 */
export interface PrepareClipResponse {
  segments: ClipSegment[];
  total_bytes: number /* uint64 */;
  duration_ms: number /* uint64 */;
}
/**
 * CoverageSegment is one entry in CoverageResponse and in the coverage
 * SSE payload published when a camera confirms an upload.
 */
export interface CoverageSegment {
  id: string;
  start_ms: number /* uint64 */;
  end_ms: number /* uint64 */;
  has_motion: boolean;
  /**
   * UploadedToS3 distinguishes uploaded vs lazy-mode local-only
   * segments so the UI can render them differently (hatched fill,
   * "fetching…" state on scrub).
   */
  uploaded_to_s3: boolean;
}
/**
 * CoverageResponse is the body of GET /hls/{id}/coverage.
 */
export interface CoverageResponse {
  segments: CoverageSegment[];
}
/**
 * TierInfo is the per-tier entry returned by GET /api/v1/billing/tiers.
 * For paid tiers the ID is a Stripe price ID (e.g. "price_1ABC..."); for
 * the free tier the ID is the literal string "free". Nil limits mean
 * unlimited. Price/currency/interval are zero for the free tier.
 */
export interface TierInfo {
  id: string;
  name: string;
  camera_limit?: number /* int */;
  storage_gb?: number /* int */;
  price_cents: number /* int64 */;
  currency: string;
  interval: string; // "month" / "year" / ""
}
/**
 * ListTiersResponse is the body of GET /api/v1/billing/tiers.
 */
export interface ListTiersResponse {
  tiers: TierInfo[];
}
/**
 * SubscriptionResponse is the body of GET /api/v1/billing/subscription.
 * Tier carries the current tier identifier (Stripe price ID or "free");
 * TierName is the human-readable display name from the Stripe product, or
 * "Free" for the unpaid tier.
 */
export interface SubscriptionResponse {
  tier: string;
  tier_name: string;
}
/**
 * UsageResponse is the body of GET /api/v1/billing/usage.
 */
export interface UsageResponse {
  cameras_count: number /* int64 */;
  storage_bytes: number /* uint64 */;
  camera_limit?: number /* int */;
  storage_limit_gb?: number /* int */;
}
/**
 * CheckoutRequest is the body of POST /api/v1/billing/checkout.
 */
export interface CheckoutRequest {
  tier: string;
  success_url: string;
  cancel_url: string;
}
/**
 * CheckoutResponse is the body of POST /api/v1/billing/checkout on success.
 */
export interface CheckoutResponse {
  url: string;
}
/**
 * PortalRequest is the body of POST /api/v1/billing/portal.
 */
export interface PortalRequest {
  return_url: string;
}
/**
 * PortalResponse is the body of POST /api/v1/billing/portal on success.
 */
export interface PortalResponse {
  url: string;
}
/**
 * AdminBillingTier is the per-price entry returned by GET
 * /api/v1/admin/billing/tiers. Unlike the public TierInfo — which only
 * surfaces tiers that already have valid ghostcam metadata — this struct
 * describes every active Stripe price in the account, including those
 * that have not yet been configured. The admin UI uses it to render an
 * editable table so the operator can see all products and assign limits.
 */
export interface AdminBillingTier {
  price_id: string;
  product_id: string;
  product_name: string;
  price_cents: number /* int64 */;
  currency: string;
  interval: string;
  /**
   * Raw metadata strings as stored on the Stripe product. Empty string
   * means the key is unset. The admin UI converts these to numbers or
   * the "Unlimited" label for display.
   */
  camera_limit_raw: string;
  storage_gb_raw: string;
  /**
   * Configured is true when both metadata keys are present — i.e. the
   * product is complete enough for the tier cache to accept it.
   */
  configured: boolean;
}
/**
 * AdminListBillingTiersResponse is the body of GET
 * /api/v1/admin/billing/tiers.
 */
export interface AdminListBillingTiersResponse {
  tiers: AdminBillingTier[];
}
/**
 * AdminUpdateBillingTierRequest is the body of PATCH
 * /api/v1/admin/billing/tiers/{priceID}. Either limit field set to null
 * means "unlimited" for that dimension. Name is optional — omit or pass
 * an empty string to leave the product name unchanged. The two limit
 * fields are always applied together to prevent half-configured products.
 */
export interface AdminUpdateBillingTierRequest {
  camera_limit?: number /* int */;
  storage_gb?: number /* int */;
  name?: string;
}
/**
 * AdminCreateBillingTierRequest is the body of POST
 * /api/v1/admin/billing/tiers. Creates a brand-new Stripe product and a
 * single recurring price on it in one call. The server validates the
 * inputs and, on success, refreshes the tier cache so the new tier
 * appears immediately in the public settings dialog.
 */
export interface AdminCreateBillingTierRequest {
  name: string;
  camera_limit?: number /* int */; // null = unlimited
  storage_gb?: number /* int */; // null = unlimited
  price_cents: number /* int64 */; // non-negative; 0 rejected for paid tiers
  currency: string; // 3-letter ISO, e.g. "usd"
  interval: string; // "month" or "year"
}
/**
 * AdminArchiveBillingTierRequest is the body of POST
 * /api/v1/admin/billing/tiers/{priceID}/archive. Archives the Stripe
 * price (and the product if this was its last active price). If the
 * price has live subscribers the server returns 409 with an
 * ActiveSubscribers count unless Confirm is true — the UI uses this
 * to gate a "yes, I know, archive anyway" dialog so CFOs don't
 * accidentally orphan a paid customer.
 */
export interface AdminArchiveBillingTierRequest {
  confirm: boolean;
}
/**
 * AdminArchiveConflictResponse is returned with HTTP 409 when the
 * archive target still has active subscribers and Confirm was false.
 * The UI uses the count to phrase an informed confirmation prompt.
 */
export interface AdminArchiveConflictResponse {
  error: string;
  active_subscribers: number /* int64 */;
}
/**
 * AdminBillingTierSubscribersResponse is the body of
 * GET /api/v1/admin/billing/tiers/{priceID}/subscribers.
 * A tiny probe used by the Reprice dialog to tell the admin how many
 * people will be affected before they commit.
 */
export interface AdminBillingTierSubscribersResponse {
  active_subscribers: number /* int64 */;
}
/**
 * AdminRepriceBillingTierRequest is the body of POST
 * /api/v1/admin/billing/tiers/{priceID}/reprice.
 * Stripe prices are immutable — the only way to "change" a price is
 * to create a new one on the same product and archive the old one.
 * This endpoint wraps that dance in one atomic admin operation and,
 * optionally, migrates existing subscribers off the old price.
 * 	PriceCents                  New amount, in the minor currency unit.
 * 	                            Currency and interval are copied from
 * 	                            the existing price — Stripe does not
 * 	                            allow changing those on a subscription.
 * 	MigrateSubscribers          If true, every active subscription on
 * 	                            the old price gets its item updated
 * 	                            to the new price ID in one call.
 * 	Prorate                     Only meaningful when MigrateSubscribers
 * 	                            is true. true = Stripe calculates
 * 	                            prorations for the switch; false =
 * 	                            no prorations, customer is on the new
 * 	                            price starting next invoice.
 * 	ConfirmDroppingSubscribers  Only meaningful when MigrateSubscribers
 * 	                            is false and the old price has >0
 * 	                            active subscribers. Admin is
 * 	                            explicitly accepting that those
 * 	                            subscribers will be dropped to free
 * 	                            on their next API call.
 */
export interface AdminRepriceBillingTierRequest {
  price_cents: number /* int64 */;
  migrate_subscribers: boolean;
  prorate: boolean;
  confirm_dropping_subscribers: boolean;
}
/**
 * AdminRepriceBillingTierResponse is the success body of reprice.
 * Carries the fresh admin tier list plus the count of subscribers
 * that were migrated so the UI can surface feedback.
 */
export interface AdminRepriceBillingTierResponse {
  tiers: AdminBillingTier[];
  migrated_count: number /* int */;
}
/**
 * AdminUser is a platform-wide view of a user for the admin Users
 * section. Joined with admin status, subscription tier, and camera
 * count so rendering the list never requires a per-row fan-out.
 * `Tier` is the raw tier identifier stored on the subscription row
 * (either "free" or a Stripe price ID). `TierName` is the resolved
 * display name from the billing cache — "Free", "Ghostcam Pro", etc.
 * The UI should render TierName; Tier stays available for equality
 * comparisons and debugging drift.
 */
export interface AdminUser {
  user_id: string;
  email: string;
  display_name: string;
  created_at: number /* int64 */;
  verified_at?: number /* int64 */;
  disabled_at?: number /* int64 */;
  deleted_at?: number /* int64 */;
  is_admin: boolean;
  tier: string;
  tier_name: string;
  camera_count: number /* int64 */;
}
/**
 * AdminListUsersResponse is the body of GET /api/v1/admin/users.
 */
export interface AdminListUsersResponse {
  users: AdminUser[];
}
/**
 * AdminCreateUserRequest is the body of POST /api/v1/admin/users.
 * The admin supplies email + display name; the server generates a
 * random initial password and returns it in the response exactly once.
 */
export interface AdminCreateUserRequest {
  email: string;
  display_name: string;
}
/**
 * AdminCreateUserResponse is the success body of POST /api/v1/admin/users.
 * The server sends an invite email to the new user with a set-password
 * link — the admin does not need to share credentials manually.
 */
export interface AdminCreateUserResponse {
  user: AdminUser;
}
/**
 * AdminUpdateUserRequest is the body of PATCH /api/v1/admin/users/{id}.
 * Today the only supported mutation is toggling the disabled flag; the
 * struct uses a pointer so "not sent" is distinct from "set to false".
 */
export interface AdminUpdateUserRequest {
  disabled?: boolean;
}
/**
 * AdminResetPasswordResponse is the success body of POST
 * /api/v1/admin/users/{id}/reset-password. Shape matches the create
 * response so the UI can reuse its one-time-password reveal dialog.
 */
export interface AdminResetPasswordResponse {
  generated_password: string;
}
/**
 * AdminCamera is a platform-wide view of a camera for the admin
 * Cameras section. Joined with owner email so the UI doesn't have to
 * secondary-fetch against the users list for each row.
 */
export interface AdminCamera {
  device_id: string;
  display_name: string;
  user_id: string;
  owner_email: string;
  enrolled_at: number /* int64 */;
  last_seen_at?: number /* int64 */;
}
/**
 * AdminListCamerasResponse is the body of GET /api/v1/admin/cameras.
 */
export interface AdminListCamerasResponse {
  cameras: AdminCamera[];
}
/**
 * AdminReassignCameraRequest is the body of PATCH
 * /api/v1/admin/cameras/{deviceID}. The server validates that the
 * target user isn't already at their tier limit and rejects with 409
 * if they are — reassignment never silently starves an existing camera.
 */
export interface AdminReassignCameraRequest {
  user_id: string;
}
/**
 * AdminReassignCameraConflictResponse is the HTTP 409 body returned
 * when the target user's tier limit would be exceeded by the move.
 * Shape mirrors AdminArchiveConflictResponse so the UI can handle
 * 409 with a single pattern.
 */
export interface AdminReassignCameraConflictResponse {
  error: string;
  camera_limit: number /* int */;
  camera_count: number /* int64 */;
}
/**
 * ClientLogEntry is the body of POST /api/v1/client-log. The endpoint is
 * gated behind an authenticated session and the UI only fires it when
 * the "Client error logging" developer setting is enabled, so there is no
 * privacy surprise — the user deliberately opts in when they need remote
 * debugging from a mobile browser.
 */
export interface ClientLogEntry {
  /**
   * Level maps to slog levels: "debug", "info", "warn", "error".
   * Unknown values fall back to "info".
   */
  level: string;
  /**
   * Source is a free-form tag for grepping (e.g. "hls", "billing").
   */
  source: string;
  /**
   * Message is the main log line.
   */
  message: string;
  /**
   * UserAgent and URL are optional context captured by the client.
   */
  user_agent?: string;
  url?: string;
  /**
   * Context is an open-ended string map for structured extras
   * (e.g. HLS error type / status code / device ID).
   */
  context?: { [key: string]: string};
}
/**
 * TokenInfo is the per-token entry returned by GET /api/v1/tokens.
 */
export interface TokenInfo {
  token_id: string;
  label: string;
  created_at: number /* int64 */;
  expires_at?: number /* int64 */;
  last_used_at?: number /* int64 */;
}
/**
 * CreateTokenRequest is the body of POST /api/v1/tokens.
 */
export interface CreateTokenRequest {
  label: string;
  expires_at?: number /* int64 */;
}
/**
 * CreateTokenResponse is the body of POST /api/v1/tokens — the raw token
 * is returned exactly once.
 */
export interface CreateTokenResponse {
  token_id: string;
  token: string;
}
/**
 * QRRequest is the body of POST /api/v1/cameras/enroll/qr. Empty body is
 * valid; TTLHours defaults to 24 (max 168).
 */
export interface QRRequest {
  wifi_ssid?: string;
  wifi_password?: string;
  ttl_hours?: number /* uint64 */;
}
/**
 * QRResponse is the body of GET/POST /api/v1/cameras/enroll/qr — the
 * JSON payload that the UI encodes into a QR code for the camera to scan.
 */
export interface QRResponse {
  payload: string;
  token: string;
  expires_at: number /* int64 */;
}
/**
 * EventEntry is one stored notification. Returned by GET /api/v1/events.
 */
export interface EventEntry {
  id: string;
  type: string;
  device_id: string;
  data: string; // raw JSON string (shape depends on Type)
  created_at: number /* uint64 */;
  read: boolean;
  dismissed: boolean;
}
/**
 * ListEventsResponse is the body of GET /api/v1/events.
 */
export interface ListEventsResponse {
  events: EventEntry[];
}
/**
 * UnreadCountResponse is the body of GET /api/v1/events/unread.
 */
export interface UnreadCountResponse {
  count: number /* int64 */;
}
/**
 * EventsSyncPayload is the body published to the per-user `events_sync:<user_id>`
 * Redis channel whenever a viewer reads / dismisses events. Other viewer tabs
 * pick this up over SSE and update their local state.
 */
export interface EventsSyncPayload {
  action: string; // "read" | "read_all" | "dismiss"
  event_id?: string;
}
/**
 * FirmwareRelease is the per-version metadata inside FirmwareLatestResponse.
 */
export interface FirmwareRelease {
  version: string;
  download_url: string;
  sha256?: string;
}
/**
 * FirmwareLatestResponse is the body of GET /api/v1/firmware/latest.
 * Release is nil when no firmware has been uploaded.
 */
export interface FirmwareLatestResponse {
  release?: FirmwareRelease;
}
/**
 * FirmwareUploadResponse is the body of POST /api/v1/admin/firmware on success.
 */
export interface FirmwareUploadResponse {
  version: string;
  size_bytes: number /* int */;
  sha256: string;
}
/**
 * FirmwareMeta is the shape stored at `firmware:latest:meta` in Redis as
 * JSON. Not an HTTP response, but part of the admin-facing contract.
 */
export interface FirmwareMeta {
  version: string;
  s3_key: string;
  size_bytes: number /* int */;
  sha256: string;
}
/**
 * PiImage is a single downloadable Pi device image served by
 * GET /api/v1/firmware/images. One per device (zero2w / pi4 / pi5).
 */
export interface PiImage {
  device: string;
  version: string;
  download_url: string;
  size_bytes: number /* int64 */;
  sha256: string;
}
/**
 * PiImagesResponse is the body of GET /api/v1/firmware/images.
 * Only populated devices are included — if the webhook has not ingested
 * a given device yet, it is omitted.
 */
export interface PiImagesResponse {
  images: PiImage[];
}
/**
 * TelemetryStreamEvent is the payload of the SSE `telemetry` event, emitted
 * for every camera telemetry update.
 */
export interface TelemetryStreamEvent {
  device_id: string;
  telemetry?: TelemetryEntry;
}
/**
 * MotionEvent is the payload of the SSE `motion_detected` event and the
 * corresponding `events:<user_id>` stream entry. EventID is the Redis
 * stream ID; it is empty when the payload is persisted to the stream
 * (the stream ID is assigned by Redis at XADD time) and non-empty when
 * it is republished for SSE consumers.
 */
export interface MotionEvent {
  event_id?: string;
  device_id: string;
  segment_id: string;
  start_ts: number /* uint64 */;
  end_ts: number /* uint64 */;
}
/**
 * CoveragePayload is the payload of the SSE `coverage` event, published
 * whenever a camera confirms a batch of uploaded segments.
 */
export interface CoveragePayload {
  device_id: string;
  segments: CoverageSegment[];
}
/**
 * StorageCappedEvent is the payload of the SSE `storage_capped` event,
 * published when a camera's upload would exceed the user's tier limit.
 */
export interface StorageCappedEvent {
  event_id?: string;
  user_id: string;
  device_id: string;
  storage_bytes: number /* uint64 */;
  limit_gb: number /* int */;
}
/**
 * CameraLimitExceededEvent is the payload of the SSE event emitted on the
 * `storage_capped:<user_id>` channel when a Stripe subscription change
 * drops the user below their current camera count.
 */
export interface CameraLimitExceededEvent {
  event_id?: string;
  user_id: string;
  camera_count: number /* int64 */;
  camera_limit: number /* int */;
  tier: string;
}
