// Code generated by tygo. DO NOT EDIT.

//////////
// source: telemetry.go

/**
 * TelemetryDatagram contains sensor readings from the camera.
 * Pointer fields implement omitempty — only non-nil fields are serialized.
 */
export interface TelemetryDatagram {
  /**
   * Unix milliseconds, camera clock.
   */
  ts: number /* uint64 */;
  /**
   * WiFi signal strength (dBm).
   */
  sig?: number /* int8 */;
  /**
   * SoC temperature (°C).
   */
  temp?: number /* uint32 */;
  /**
   * Capture frame rate.
   */
  fps?: number /* float32 */;
  /**
   * Video bitrate (kbps).
   */
  kbps?: number /* uint32 */;
  /**
   * CPU usage (%).
   */
  cpu?: number /* uint32 */;
  /**
   * Memory usage (MB).
   */
  mem?: number /* uint32 */;
  /**
   * Uptime (seconds).
   */
  uptime?: number /* uint32 */;
  /**
   * GPS latitude.
   */
  lat?: number /* float64 */;
  /**
   * GPS longitude.
   */
  lon?: number /* float64 */;
  /**
   * GPS altitude (metres).
   */
  alt?: number /* float32 */;
  /**
   * GPS fix quality: 0=none, 1=2D, 2=3D.
   */
  gps_fix?: number /* uint8 */;
}

//////////
// source: types.go
/*
Package common defines shared request/response types for the camera-server HTTP API.

Both consumers of this package (the Go server and the Python camera) get
their types via codegen from these struct definitions:
  - tygo emits TypeScript to ui/src/lib/api-types/ (driven by the
    directive in server/apitypes/apitypes.go).
  - tools/pydanticgen emits pydantic v2 models to
    camera/ghostcam/wire/ (driven by the directive below).

Both run together as part of `go generate ./...`. CI fails if either
generated tree is stale.
*/

/**
 * ProvisionRequest is sent by the camera during provisioning. The camera
 * sends its ed25519 public key for registration (like adding to SSH
 * authorized_keys). The server derives device_id from the public key.
 */
export interface ProvisionRequest {
  token: string;
  device_serial: string;
  public_key: string; // hex-encoded ed25519 public key (64 chars)
  fw_version?: string;
}
/**
 * ProvisionResponse acknowledges key registration. No secret is returned.
 */
export interface ProvisionResponse {
  device_id: string; // echoed back for confirmation
  status: string; // "registered"
}
/**
 * TelemetryPollRequest is sent by the camera every 10s with current sensor readings.
 */
export interface TelemetryPollRequest {
  telemetry: TelemetryDatagram;
  fw_version?: string;
}
/**
 * TelemetryPollResponse contains any pending commands for the camera.
 */
export interface TelemetryPollResponse {
  commands?: CameraCommand[];
}
/**
 * CameraCommand is a tagged union of commands the server can send to a camera.
 * The Type field determines which other fields are populated.
 */
export interface CameraCommand {
  type: string;
  mode?: string; // set_recording_mode
  resolution?: string; // set_resolution
  ssid?: string; // network_config, remove_network
  psk?: string; // network_config
}
/**
 * PresignRequest requests presigned PUT URLs and confirms previously uploaded segments.
 */
export interface PresignRequest {
  count: number /* uint32 */;
  uploaded?: UploadedSegment[];
}
/**
 * UploadedSegment confirms a successfully uploaded segment.
 */
export interface UploadedSegment {
  segment_id: string;
  start_ts: number /* uint64 */;
  end_ts: number /* uint64 */;
  size_bytes: number /* uint64 */;
  has_motion?: boolean;
}
/**
 * PresignedUrl is a presigned URL for uploading a segment to S3/Tigris.
 */
export interface PresignedUrl {
  segment_id: string;
  s3_key: string;
  put_url: string;
  expires_at: number /* uint64 */;
}
/**
 * PresignResponse contains presigned URLs for segment uploads.
 */
export interface PresignResponse {
  urls: PresignedUrl[];
  init_url?: PresignedUrl;
  storage_capped?: boolean;
}
/**
 * QRPayload is the JSON shape encoded inside a provisioning QR code. The
 * viewer UI builds it (via the server's EnrollmentQR handler), displays
 * it as a QR image, and the camera parses it on first boot after scan.
 * Field names are single letters to keep the QR code compact.
 */
export interface QRPayload {
  s: string; // server base URL
  t: string; // one-time provision token
  w?: string; // optional Wi-Fi SSID to join
  p?: string; // optional Wi-Fi password
}
