// Code generated by tygo. DO NOT EDIT.

//////////
// source: telemetry.go

/**
 * TelemetryDatagram contains sensor readings from the camera.
 * Pointer fields implement omitempty — only non-nil fields are serialized.
 */
export interface TelemetryDatagram {
  /**
   * Unix milliseconds, camera clock.
   */
  ts: number /* uint64 */;
  /**
   * WiFi signal strength (dBm).
   */
  sig?: number /* int8 */;
  /**
   * SoC temperature (°C).
   */
  temp?: number /* uint32 */;
  /**
   * Capture frame rate.
   */
  fps?: number /* float32 */;
  /**
   * Video bitrate (kbps).
   */
  kbps?: number /* uint32 */;
  /**
   * CPU usage (%).
   */
  cpu?: number /* uint32 */;
  /**
   * Memory usage (MB).
   */
  mem?: number /* uint32 */;
  /**
   * Uptime (seconds).
   */
  uptime?: number /* uint32 */;
  /**
   * GPS latitude.
   */
  lat?: number /* float64 */;
  /**
   * GPS longitude.
   */
  lon?: number /* float64 */;
  /**
   * GPS altitude (metres).
   */
  alt?: number /* float32 */;
  /**
   * GPS fix quality: 0=none, 1=2D, 2=3D.
   */
  gps_fix?: number /* uint8 */;
  /**
   * Currently effective power mode after schedule + battery rule
   * resolution: "live" | "standby" | "sleep". Lets the server (and UI)
   * see what the camera is actually doing right now, which can differ
   * from the manually-set mode when a schedule or battery rule is
   * overriding it.
   */
  power_mode?: string;
  /**
   * Currently effective upload mode: "proactive" | "lazy". Same
   * reasoning as PowerMode.
   */
  upload_mode?: string;
  /**
   * Battery state-of-charge (0-100). Only set when a battery-sensing
   * HAT (PiSugar / generic UPS) is wired up via
   * platform/battery.py; absent on grid-powered cameras.
   */
  battery_pct?: number /* uint8 */;
  /**
   * Motion-gated upload counters since boot. Lets the field measure
   * bandwidth savings on cameras running recording_mode='motion':
   * uploaded counts segments that went to S3, skipped counts segments
   * that were posted to local-manifest instead. Absent on cameras
   * running recording_mode='constant' (always zero, no signal).
   */
  motion_segments_uploaded?: number /* uint32 */;
  motion_segments_skipped?: number /* uint32 */;
  /**
   * Performance / health metrics. All optional; absent fields stay
   * out of the JSON envelope so a missing capability (no gpsd, no
   * modem) doesn't surface as zero.
   * SegmentUploadP95Ms: 95th percentile of the time from segment file
   * close to S3 PUT 200, sampled over the most recent ~50 uploads.
   * Leading indicator of network or presign-path slowdown.
   */
  segment_upload_p95_ms?: number /* uint32 */;
  /**
   * SegmentUploadRetries: cumulative retry count since boot. Differs
   * from a "failed uploads" counter: a single eventually-successful
   * upload that hits 2 retries adds 2 here.
   */
  segment_upload_retries?: number /* uint32 */;
  /**
   * SegmentQueueDepth: instantaneous depth of the asyncio segment
   * queue feeding the upload loop. Saturation means the camera is
   * producing segments faster than it can upload them — leading
   * indicator before storage_capped fires.
   */
  segment_queue_depth?: number /* uint8 */;
  /**
   * LiveWSBytesPerSec: bytes pushed over the live WebSocket since the
   * last telemetry tick, divided by the tick interval. Tracks WebRTC
   * viewer egress independently of S3 upload bandwidth.
   */
  live_ws_bytes_per_sec?: number /* uint32 */;
  /**
   * LiveWSDroppedFrames: cumulative count of frames dropped by the
   * LiveRelay ring buffer (drop-oldest under back-pressure). Any
   * non-zero number means the consumer (server) is slower than the
   * camera's encode rate.
   */
  live_ws_dropped_frames?: number /* uint32 */;
  /**
   * GpsdQueryMs: wall-time of the most recent gpsd query in
   * milliseconds. Catches gpsd hiccups (slow socket, parse errors)
   * that don't surface as fix-quality changes.
   */
  gpsd_query_ms?: number /* uint16 */;
  /**
   * EventLoopLagMs: scheduling latency for asyncio.sleep(0) measured
   * at the schedule-ticker task. A sustained non-zero here = some
   * task is blocking the loop synchronously.
   */
  event_loop_lag_ms?: number /* uint16 */;
  /**
   * DiskUsedPct: percent disk used at segment_dir's filesystem.
   * Complements local_storage_cap_bytes for visibility into
   * whether the cap is doing its job.
   */
  disk_used_pct?: number /* uint8 */;
  /**
   * ModemRAT: cellular Radio Access Technology in use (e.g. "LTE",
   * "5G_NSA", "WCDMA"). Pairs with the existing Sig dBm so the UI
   * can show "−95 dBm LTE" vs "−95 dBm 3G". Absent when wired.
   */
  modem_rat?: string;
}

//////////
// source: types.go
/*
Package common defines shared request/response types for the camera-server HTTP API.

Both consumers of this package (the Go server and the Python camera) get
their types via codegen from these struct definitions:
  - tygo emits TypeScript to ui/src/lib/api-types/ (driven by the
    directive in server/apitypes/apitypes.go).
  - tools/pydanticgen emits pydantic v2 models to
    camera/ghostcam/wire/ (driven by the directive below).

Both run together as part of `go generate ./...`. CI fails if either
generated tree is stale.
*/

/**
 * ProvisionRequest is sent by the camera during provisioning. The camera
 * sends its ed25519 public key for registration (like adding to SSH
 * authorized_keys). The server derives device_id from the public key.
 */
export interface ProvisionRequest {
  token: string;
  device_serial: string;
  public_key: string; // hex-encoded ed25519 public key (64 chars)
  fw_version?: string;
}
/**
 * ProvisionResponse acknowledges key registration. No secret is returned.
 */
export interface ProvisionResponse {
  device_id: string; // echoed back for confirmation
  status: string; // "registered"
}
/**
 * TelemetryPollRequest is sent by the camera every 10s with current sensor readings.
 */
export interface TelemetryPollRequest {
  telemetry: TelemetryDatagram;
  fw_version?: string;
}
/**
 * TelemetryPollResponse contains any pending commands for the camera.
 * WakeLive is set when a viewer is actively trying to watch a camera that
 * is in standby mode (live WS not currently connected). The camera reads
 * this flag and proactively opens its live WebSocket so WebRTC startup
 * stays bounded by one telemetry-poll interval.
 */
export interface TelemetryPollResponse {
  commands?: CameraCommand[];
  wake_live?: boolean;
}
/**
 * CameraCommand is a tagged union of commands the server can send to a camera.
 * The Type field determines which other fields are populated.
 * Power-mode commands:
 *   - set_power_mode      → PowerMode field      (live | standby | sleep)
 *   - set_upload_mode     → UploadMode field     (proactive | lazy)
 *   - set_schedule        → Schedule field       (JSON-encoded windows)
 *   - set_battery_rules   → BatteryRules field   (JSON-encoded thresholds)
 *   - upload_segments     → SegmentIDs field     (lazy-mode on-demand fetch)
 */
export interface CameraCommand {
  type: string;
  mode?: string; // set_recording_mode
  resolution?: string; // set_resolution
  ssid?: string; // network_config, remove_network
  psk?: string; // network_config
  /**
   * Power-mode commands.
   */
  power_mode?: string; // set_power_mode: "live" | "standby" | "sleep"
  upload_mode?: string; // set_upload_mode: "proactive" | "lazy"
  schedule?: string; // set_schedule: JSON list of {window, power_mode, upload_mode}
  battery_rules?: string; // set_battery_rules: JSON list of {threshold_pct, power_mode, upload_mode}
  segment_ids?: string[]; // upload_segments: priority-fetch these segments now
}
/**
 * PresignRequest requests presigned PUT URLs and confirms previously uploaded segments.
 */
export interface PresignRequest {
  count: number /* uint32 */;
  uploaded?: UploadedSegment[];
}
/**
 * UploadedSegment confirms a successfully uploaded segment.
 */
export interface UploadedSegment {
  segment_id: string;
  start_ts: number /* uint64 */;
  end_ts: number /* uint64 */;
  size_bytes: number /* uint64 */;
  has_motion?: boolean;
}
/**
 * PresignedUrl is a presigned URL for uploading a segment to S3/Tigris.
 */
export interface PresignedUrl {
  segment_id: string;
  s3_key: string;
  put_url: string;
  expires_at: number /* uint64 */;
}
/**
 * PresignResponse contains presigned URLs for segment uploads.
 */
export interface PresignResponse {
  urls: PresignedUrl[];
  init_url?: PresignedUrl;
  storage_capped?: boolean;
}
/**
 * LocalManifestRequest is the body of
 * POST /api/v1/cameras/{deviceID}/local-manifest. A lazy-mode camera
 * posts a manifest of segments it has on disk but has NOT yet uploaded
 * to S3, so the server's timeline / coverage bar can show the user
 * that footage exists even if it's not fetchable until they scrub to
 * it. On scrub, the server queues an `upload_segments` command which
 * pulls the bytes on demand.
 * Manifest entries are inserted with `uploaded_to_s3 = FALSE`. When
 * the camera later uploads a segment (because of a scrub-triggered
 * command), the presign-confirm path flips it to TRUE.
 */
export interface LocalManifestRequest {
  segments: UploadedSegment[];
}
/**
 * QRPayload is the JSON shape encoded inside a provisioning QR code. The
 * viewer UI builds it (via the server's EnrollmentQR handler), displays
 * it as a QR image, and the camera parses it on first boot after scan.
 * Field names are single letters to keep the QR code compact.
 */
export interface QRPayload {
  s: string; // server base URL
  t: string; // one-time provision token
  w?: string; // optional Wi-Fi SSID to join
  p?: string; // optional Wi-Fi password
}
