-- HLS/S3 rewrite: camera API keys, provision tokens, segment metadata.
-- Removes QUIC/mTLS identity (cert_fingerprint) in favor of API key auth.

-- Camera API keys (one per camera, obtained during provisioning)
CREATE TABLE IF NOT EXISTS camera_api_keys (
    device_id    TEXT PRIMARY KEY REFERENCES cameras(device_id) ON DELETE CASCADE,
    api_key_hash TEXT UNIQUE NOT NULL,
    created_at   BIGINT NOT NULL
);

-- One-time provisioning tokens (generated by web UI, scanned by camera via QR)
CREATE TABLE IF NOT EXISTS provision_tokens (
    token_hash  TEXT PRIMARY KEY,
    user_id     TEXT NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
    created_at  BIGINT NOT NULL,
    expires_at  BIGINT NOT NULL,
    claimed_at  BIGINT,
    device_id   TEXT REFERENCES cameras(device_id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_provision_tokens_user_id ON provision_tokens(user_id);

-- Segment metadata (one row per uploaded fMP4 segment)
CREATE TABLE IF NOT EXISTS segments (
    segment_id     TEXT PRIMARY KEY,
    device_id      TEXT NOT NULL REFERENCES cameras(device_id) ON DELETE CASCADE,
    s3_key         TEXT NOT NULL,
    start_ts       BIGINT NOT NULL,
    end_ts         BIGINT NOT NULL,
    size_bytes     BIGINT NOT NULL,
    resolution     TEXT NOT NULL DEFAULT '720p',
    created_at     BIGINT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_segments_device_time ON segments(device_id, start_ts);
CREATE INDEX IF NOT EXISTS idx_segments_device_end ON segments(device_id, end_ts);

-- Extend cameras table for new provisioning model
ALTER TABLE cameras ADD COLUMN IF NOT EXISTS device_serial TEXT UNIQUE;
ALTER TABLE cameras ADD COLUMN IF NOT EXISTS resolution TEXT NOT NULL DEFAULT '720p';
ALTER TABLE cameras ADD COLUMN IF NOT EXISTS recording_mode TEXT NOT NULL DEFAULT 'constant';

-- Pending commands queue (polled by camera via telemetry endpoint)
CREATE TABLE IF NOT EXISTS camera_commands (
    id         BIGSERIAL PRIMARY KEY,
    device_id  TEXT NOT NULL REFERENCES cameras(device_id) ON DELETE CASCADE,
    command    JSONB NOT NULL,
    created_at BIGINT NOT NULL,
    claimed_at BIGINT
);

CREATE INDEX IF NOT EXISTS idx_camera_commands_device ON camera_commands(device_id, claimed_at);

-- cert_fingerprint is no longer required (cameras auth via API key now)
ALTER TABLE cameras ALTER COLUMN cert_fingerprint DROP NOT NULL;
